name: FTP Deploy ke Hosting

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/sftp-deploy@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local-dir: ./dist
          server-dir: ${{ secrets.FTP_PATH }}

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**